### ISSUE TITLE
MaryTTS emulation and Home Assistant

### ISSUE THREAD

**Issue by hawkeye217** [rhasspy/larynx#12]
I'm having trouble setting up the [MaryTTS component](https://www.home-assistant.io/integrations/marytts/) in Home Assistant to work with Larynx. In particular, there are several parameters that can be defined in yaml. The docs give this example:

```
tts:
  - platform: marytts
    host: "localhost"
    port: 59125
    codec: "WAVE_FILE"
    voice: "cmu-slt-hsmm"
    language: "en_US"
    effect:
      Volume: "amount:2.0;"
```

Larynx is up and running and I can generate speech via localhost:59125. I'd like to use a specific voice and quality setting with Home Assistant's TTS. I tried setting the following:

```
...
    voice: "harvard-glow_tts"
    language: "en_us"
...
```

But Home Assistant's log shows an error saying that "en_us" is not a valid language ("en_US" is, though).

What are the correct parameters necessary to use a specific voice? And would it be possible to use an ``effect`` key to set the voice quality (high, medium, low)?
